version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      python-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      python-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/website"
      - "/extensions"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      npm-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      npm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
