"""Neutral, offline ingestion for reproducible public CSV dumps.

This module owns source identity, deterministic manifests, and one streaming CSV
reader.  It intentionally has no knowledge of profiles, ratings, or any other
consumer-specific schema.
"""

from __future__ import annotations

import csv
import gzip
import hashlib
import io
import json
import os
import re
import tarfile
import tempfile
from collections import deque
from collections.abc import Callable, Iterator, Mapping
from contextlib import ExitStack, contextmanager
from dataclasses import dataclass
from os import PathLike
from types import MappingProxyType
from typing import Any, BinaryIO, Literal, TypeAlias

PathInput: TypeAlias = str | PathLike[str]
PUBLIC_DUMP_MANIFEST_SCHEMA_VERSION = 1
PUBLIC_DUMP_MAX_ISSUE_DETAILS: int = 100
"""Maximum number of privacy-safe issue details retained in one read report."""
_SHA256_PATTERN = re.compile(r"[0-9a-fA-F]{64}\Z")


class PublicDumpError(RuntimeError):
    """Base error for public-dump source validation and reading failures."""


class PublicDumpChecksumError(PublicDumpError):
    """Raised before iteration when a source does not match its pinned digest."""


class PublicDumpFormatError(PublicDumpError):
    """Raised when a dump container or CSV header cannot be read."""


class PublicDumpParseError(PublicDumpError):
    """Raised for an unrecoverable CSV parse error after recording its reason."""

    def __init__(self, message: str, *, report: PublicDumpReadReport) -> None:
        super().__init__(message)
        self.report = report


@dataclass(frozen=True, slots=True)
class PublicDumpSource:
    """Pinned identity and caller-supplied provenance for one public dump.

    ``retrieved_at`` is never generated by the reader.  URL sources are valid
    manifest records, but this offline reader intentionally accepts only local
    paths and never performs network access.
    """

    name: str
    path: PathInput | None = None
    url: str | None = None
    sha256: str | None = None
    retrieved_at: str | None = None
    attribution: str = ""
    license: str = ""

    def __post_init__(self) -> None:
        if not isinstance(self.name, str) or not _valid_source_name(self.name):
            raise PublicDumpError(f"Invalid public-dump source name {self.name!r}.")

        if (self.path is None) == (self.url is None):
            raise PublicDumpError(
                f"Source {self.name!r} must have exactly one of path or url."
            )
        if self.path is not None:
            try:
                path = os.fspath(self.path)
            except TypeError as error:
                raise PublicDumpError(
                    f"Source {self.name!r} has an invalid local path."
                ) from error
            if not isinstance(path, str) or not path:
                raise PublicDumpError(
                    f"Source {self.name!r} has an invalid local path."
                )
            object.__setattr__(self, "path", path)

        if self.url is not None:
            if not isinstance(self.url, str) or not self.url.strip():
                raise PublicDumpError(f"Source {self.name!r} has an empty URL.")

        if self.sha256 is not None:
            if not isinstance(self.sha256, str) or not _SHA256_PATTERN.fullmatch(
                self.sha256
            ):
                raise PublicDumpError(f"Source {self.name!r} has an invalid SHA-256 pin.")
            object.__setattr__(self, "sha256", self.sha256.lower())

        if self.retrieved_at is not None and not isinstance(self.retrieved_at, str):
            raise PublicDumpError(
                f"Source {self.name!r} provenance field 'retrieved_at' must be a string."
            )
        for field_name in ("attribution", "license"):
            if not isinstance(getattr(self, field_name), str):
                raise PublicDumpError(
                    f"Source {self.name!r} provenance field {field_name!r} must be a string."
                )

    def to_json(self) -> dict[str, object]:
        """Return a JSON-compatible descriptor without source data."""

        value: dict[str, object] = {
            "name": self.name,
            "sha256": self.sha256,
            "retrieved_at": self.retrieved_at,
            "attribution": self.attribution,
            "license": self.license,
        }
        if self.path is not None:
            value["path"] = self.path
        if self.url is not None:
            value["url"] = self.url
        return value

    @classmethod
    def from_json(cls, value: Mapping[str, Any]) -> PublicDumpSource:
        """Load and validate one manifest source descriptor."""

        if not isinstance(value, Mapping):
            raise PublicDumpError("Public-dump manifest source must be an object.")

        def optional_string(key: str) -> str | None:
            item = value.get(key)
            if item is None:
                return None
            if not isinstance(item, str):
                raise PublicDumpError(f"Public-dump source field {key!r} must be a string.")
            return item

        def provenance_string(key: str) -> str:
            if key not in value:
                return ""
            item = value[key]
            if not isinstance(item, str):
                raise PublicDumpError(f"Public-dump source field {key!r} must be a string.")
            return item

        name = value.get("name")
        if not isinstance(name, str):
            raise PublicDumpError("Public-dump source name must be a string.")
        return cls(
            name=name,
            path=optional_string("path"),
            url=optional_string("url"),
            sha256=optional_string("sha256"),
            retrieved_at=optional_string("retrieved_at"),
            attribution=provenance_string("attribution"),
            license=provenance_string("license"),
        )


@dataclass(frozen=True, slots=True)
class PublicDumpManifest:
    """Canonical manifest for one or more pinned public-dump sources."""

    sources: tuple[PublicDumpSource, ...]
    schema_version: int = PUBLIC_DUMP_MANIFEST_SCHEMA_VERSION

    def __post_init__(self) -> None:
        if (
            not isinstance(self.schema_version, int)
            or isinstance(self.schema_version, bool)
            or self.schema_version != PUBLIC_DUMP_MANIFEST_SCHEMA_VERSION
        ):
            raise PublicDumpError(
                f"Unsupported public-dump manifest schema {self.schema_version}; "
                f"expected {PUBLIC_DUMP_MANIFEST_SCHEMA_VERSION}."
            )
        sources = tuple(self.sources)
        if not all(isinstance(source, PublicDumpSource) for source in sources):
            raise PublicDumpError("Public-dump manifest sources must be PublicDumpSource values.")
        if not sources:
            raise PublicDumpError("Public-dump manifest must contain at least one source.")
        unpinned = next((source for source in sources if source.sha256 is None), None)
        if unpinned is not None:
            raise PublicDumpError(
                f"Public-dump manifest source {unpinned.name!r} has no SHA-256 pin."
            )
        if len({source.name for source in sources}) != len(sources):
            raise PublicDumpError("Public-dump manifest source names must be unique.")
        object.__setattr__(self, "sources", tuple(sorted(sources, key=lambda source: source.name)))

    def to_json(self) -> dict[str, object]:
        return {
            "schema_version": self.schema_version,
            "sources": [source.to_json() for source in self.sources],
        }

    def to_bytes(self) -> bytes:
        """Serialize using canonical JSON ordering and a final newline."""

        return (
            json.dumps(
                self.to_json(),
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
            )
            + "\n"
        ).encode("utf-8")

    @classmethod
    def from_json(cls, value: Mapping[str, Any]) -> PublicDumpManifest:
        schema_version = value.get("schema_version") if isinstance(value, Mapping) else None
        if (
            not isinstance(schema_version, int)
            or isinstance(schema_version, bool)
            or schema_version != PUBLIC_DUMP_MANIFEST_SCHEMA_VERSION
        ):
            raise PublicDumpError("Invalid public-dump manifest schema.")
        sources = value.get("sources")
        if not isinstance(sources, list):
            raise PublicDumpError("Public-dump manifest has no sources list.")
        return cls(sources=tuple(PublicDumpSource.from_json(item) for item in sources))

    @classmethod
    def from_bytes(cls, payload: bytes) -> PublicDumpManifest:
        try:
            value = json.loads(payload.decode("utf-8"))
        except (AttributeError, UnicodeDecodeError, json.JSONDecodeError) as error:
            raise PublicDumpError(f"Could not parse public-dump manifest: {error}.") from error
        if not isinstance(value, Mapping):
            raise PublicDumpError("Public-dump manifest must be an object.")
        return cls.from_json(value)


@dataclass(frozen=True, slots=True)
class PublicDumpIssue:
    """One privacy-safe row/container issue; it contains no row values."""

    action: Literal["skip", "error"]
    reason: str
    row_number: int | None = None
    source_name: str = ""

    def __post_init__(self) -> None:
        if (
            self.action not in {"skip", "error"}
            or not isinstance(self.reason, str)
            or not self.reason
        ):
            raise PublicDumpError("Public-dump issue has an invalid action or reason.")
        if self.row_number is not None and (
            not isinstance(self.row_number, int)
            or isinstance(self.row_number, bool)
            or self.row_number < 1
        ):
            raise PublicDumpError("Public-dump issue row number must be positive.")
        if not isinstance(self.source_name, str):
            raise PublicDumpError("Public-dump issue source name must be a string.")

    def to_json(self) -> dict[str, object]:
        # Action is represented by the report's skip/error reason maps.  Keep
        # persisted issue records limited to source identity and diagnostics.
        value: dict[str, object] = {
            "source_name": self.source_name,
            "reason": self.reason,
        }
        if self.row_number is not None:
            value["row_number"] = self.row_number
        return value


@dataclass(frozen=True, slots=True)
class PublicDumpReadReport:
    """Aggregate counts and structured issues safe to persist or display."""

    rows_seen: int
    rows_yielded: int
    rows_skipped: int
    skip_reasons: Mapping[str, int]
    error_reasons: Mapping[str, int]
    issues: tuple[PublicDumpIssue, ...] = ()
    source_name: str = ""
    omitted_issue_details: int = 0

    def __post_init__(self) -> None:
        for value in (self.rows_seen, self.rows_yielded, self.rows_skipped):
            if not isinstance(value, int) or isinstance(value, bool) or value < 0:
                raise PublicDumpError("Public-dump read counts cannot be negative.")
        if self.rows_yielded + self.rows_skipped != self.rows_seen:
            raise PublicDumpError("Public-dump read counts do not reconcile.")
        for reason_counts in (self.skip_reasons, self.error_reasons):
            if any(
                not isinstance(key, str) or not key
                for key in reason_counts
            ):
                raise PublicDumpError("Public-dump issue reasons must be non-empty strings.")
            if any(
                not isinstance(value, int)
                or isinstance(value, bool)
                or value < 0
                for value in reason_counts.values()
            ):
                raise PublicDumpError("Public-dump issue counts must be non-negative integers.")
        if not isinstance(self.source_name, str):
            raise PublicDumpError("Public-dump report source name must be a string.")
        if (
            not isinstance(self.omitted_issue_details, int)
            or isinstance(self.omitted_issue_details, bool)
            or self.omitted_issue_details < 0
        ):
            raise PublicDumpError(
                "Public-dump omitted issue-detail count must be a non-negative integer."
            )
        issues = tuple(self.issues)
        if len(issues) > PUBLIC_DUMP_MAX_ISSUE_DETAILS:
            raise PublicDumpError(
                "Public-dump report retained issue details exceed the maximum."
            )
        if not all(isinstance(issue, PublicDumpIssue) for issue in issues):
            raise PublicDumpError("Public-dump report issues must be PublicDumpIssue values.")
        total_issue_events = sum(self.skip_reasons.values()) + sum(
            self.error_reasons.values()
        )
        if len(issues) + self.omitted_issue_details != total_issue_events:
            raise PublicDumpError(
                "Public-dump report issue details do not reconcile with issue counts."
            )
        object.__setattr__(self, "skip_reasons", MappingProxyType(dict(self.skip_reasons)))
        object.__setattr__(self, "error_reasons", MappingProxyType(dict(self.error_reasons)))
        object.__setattr__(self, "issues", issues)

    def to_json(self) -> dict[str, object]:
        return {
            "source_name": self.source_name,
            "rows_seen": self.rows_seen,
            "rows_yielded": self.rows_yielded,
            "rows_skipped": self.rows_skipped,
            "skip_reasons": dict(sorted(self.skip_reasons.items())),
            "error_reasons": dict(sorted(self.error_reasons.items())),
            "issues": [issue.to_json() for issue in self.issues],
            "omitted_issue_details": self.omitted_issue_details,
        }


@dataclass(frozen=True, slots=True)
class PublicDumpReadResult:
    """Transient valid rows and their privacy-safe report for one read."""

    rows: tuple[Mapping[str, str], ...]
    report: PublicDumpReadReport

    def __post_init__(self) -> None:
        object.__setattr__(self, "rows", tuple(self.rows))


class _ReportBuilder:
    __slots__ = (
        "source_name",
        "rows_seen",
        "rows_yielded",
        "rows_skipped",
        "skip_reasons",
        "error_reasons",
        "issues",
        "omitted_issue_details",
    )

    def __init__(self, *, source_name: str) -> None:
        self.source_name = source_name
        self.rows_seen = 0
        self.rows_yielded = 0
        self.rows_skipped = 0
        self.skip_reasons: dict[str, int] = {}
        self.error_reasons: dict[str, int] = {}
        self.issues: list[PublicDumpIssue] = []
        self.omitted_issue_details = 0

    def _record_issue(self, issue: PublicDumpIssue) -> None:
        if len(self.issues) < PUBLIC_DUMP_MAX_ISSUE_DETAILS:
            self.issues.append(issue)
        else:
            self.omitted_issue_details += 1

    def skip(self, *, row_number: int, reason: str) -> None:
        self.rows_seen += 1
        self.rows_skipped += 1
        self.skip_reasons[reason] = self.skip_reasons.get(reason, 0) + 1
        self._record_issue(
            PublicDumpIssue(
                action="skip",
                reason=reason,
                row_number=row_number,
                source_name=self.source_name,
            )
        )

    def yield_row(self) -> None:
        self.rows_seen += 1
        self.rows_yielded += 1

    def error(self, *, reason: str, row_number: int | None = None) -> None:
        self.error_reasons[reason] = self.error_reasons.get(reason, 0) + 1
        self._record_issue(
            PublicDumpIssue(
                action="error",
                reason=reason,
                row_number=row_number,
                source_name=self.source_name,
            )
        )

    def build(self) -> PublicDumpReadReport:
        return PublicDumpReadReport(
            source_name=self.source_name,
            rows_seen=self.rows_seen,
            rows_yielded=self.rows_yielded,
            rows_skipped=self.rows_skipped,
            skip_reasons=self.skip_reasons,
            error_reasons=self.error_reasons,
            issues=tuple(self.issues),
            omitted_issue_details=self.omitted_issue_details,
        )


class _CSVLineTracker:
    """Track physical CSV lines without changing the parser's input."""

    __slots__ = (
        "_stream",
        "_in_quotes",
        "_record_start",
        "_on_blank_row",
        "record_starts",
        "line_number",
    )

    def __init__(
        self,
        stream: Iterator[str],
        *,
        on_blank_row: Callable[[int], None],
    ) -> None:
        self._stream = stream
        self._in_quotes = False
        self._record_start: int | None = None
        self._on_blank_row = on_blank_row
        self.record_starts: deque[int] = deque()
        self.line_number = 0

    def __iter__(self) -> _CSVLineTracker:
        return self

    def __next__(self) -> str:
        line = next(self._stream)
        self.line_number += 1
        was_in_quotes = self._in_quotes
        if not was_in_quotes and line.rstrip("\r\n") == "":
            self._on_blank_row(self.line_number)
        elif not was_in_quotes:
            self._record_start = self.line_number

        self._scan_quotes(line)
        if self._record_start is not None and not self._in_quotes:
            self.record_starts.append(self._record_start)
            self._record_start = None
        return line

    def _scan_quotes(self, line: str) -> None:
        field_start = True
        index = 0
        while index < len(line):
            character = line[index]
            if character in "\r\n":
                index += 1
                continue
            if self._in_quotes:
                if character == '"':
                    if index + 1 < len(line) and line[index + 1] == '"':
                        index += 2
                        continue
                    self._in_quotes = False
                    field_start = False
                index += 1
                continue
            if character == ",":
                field_start = True
            elif character == '"' and field_start:
                self._in_quotes = True
            else:
                field_start = False
            index += 1

    def discard_record_start(self) -> None:
        if self.record_starts:
            self.record_starts.popleft()

    def next_record_start(self, fallback: int) -> int:
        if self.record_starts:
            return self.record_starts.popleft()
        return fallback


class _CleanupIterator(Iterator[Mapping[str, str]]):
    """Close a parser and remove its private snapshot when iteration ends."""

    __slots__ = ("_iterator", "_snapshot_path", "_closed")

    def __init__(
        self,
        iterator: Iterator[Mapping[str, str]],
        *,
        snapshot_path: str,
    ) -> None:
        self._iterator = iterator
        self._snapshot_path = snapshot_path
        self._closed = False

    def __iter__(self) -> _CleanupIterator:
        return self

    def __next__(self) -> Mapping[str, str]:
        if self._closed:
            raise StopIteration
        try:
            return next(self._iterator)
        except BaseException:
            self.close()
            raise

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        try:
            close = getattr(self._iterator, "close", None)
            if close is not None:
                close()
        finally:
            try:
                os.unlink(self._snapshot_path)
            except OSError:
                pass

    def __del__(self) -> None:
        self.close()


class PublicDumpReader:
    """Verify and stream one local CSV, gzip, or tar public dump."""

    def __init__(self, source: PublicDumpSource | PathInput) -> None:
        if isinstance(source, PublicDumpSource):
            self.source = source
        else:
            path = os.fspath(source)
            if not isinstance(path, str) or not path:
                raise PublicDumpError(
                    "Public-dump path must be a non-empty string or path-like value."
                )
            self.source = PublicDumpSource(name=os.path.basename(path), path=path)
        self._report: PublicDumpReadReport | None = None
        self._container: BinaryIO | None = None

    @property
    def report(self) -> PublicDumpReadReport | None:
        """Return the report from the most recently exhausted read, if any."""

        return self._report

    @property
    def bytes_read(self) -> int:
        """Return how many bytes of the file on disk the open read has consumed.
        For a gzip dump this counts compressed bytes, so it reaches the file size at the end.
        """

        container = self._container
        if container is None or container.closed:
            return 0
        return container.tell()

    def iter_rows(self) -> Iterator[Mapping[str, str]]:
        """Validate before returning a generator, then yield valid CSV mappings."""

        self._report = None
        path = self._local_path()
        if self.source.sha256 is None:
            return self._iter_rows(path=path)
        snapshot_path = _snapshot_and_verify(source=self.source, path=path)
        return _CleanupIterator(
            self._iter_rows(path=snapshot_path),
            snapshot_path=snapshot_path,
        )

    def _local_path(self) -> str:
        if self.source.path is None:
            raise PublicDumpFormatError(
                f"Public-dump source {self.source.name!r} has no local path; "
                "network access is disabled."
            )
        path = os.fspath(self.source.path)
        if not os.path.isfile(path):
            raise PublicDumpFormatError(f"Public-dump source does not exist: {path}.")
        return path

    def _iter_rows(self, *, path: str) -> Iterator[Mapping[str, str]]:
        builder = _ReportBuilder(source_name=self.source.name)
        try:
            with _open_text(path=path) as (text_file, container):
                self._container = container
                tracker = _CSVLineTracker(
                    text_file,
                    on_blank_row=lambda row_number: builder.skip(
                        row_number=row_number, reason="blank_row"
                    ),
                )
                reader = csv.DictReader(tracker, strict=True)
                try:
                    fieldnames = reader.fieldnames
                except csv.Error as error:
                    builder.error(reason="malformed_csv")
                    self._report = builder.build()
                    raise PublicDumpParseError(
                        f"Malformed public-dump CSV {self.source.name}: {error}.",
                        report=self._report,
                    ) from error
                _validate_header(fieldnames=fieldnames, source_name=self.source.name)
                tracker.discard_record_start()
                for row in reader:
                    row_number = tracker.next_record_start(
                        fallback=reader.line_num,
                    )
                    if None in row:
                        builder.skip(row_number=row_number, reason="extra_fields")
                        continue
                    if any(value is None for value in row.values()):
                        builder.skip(row_number=row_number, reason="missing_fields")
                        continue
                    builder.yield_row()
                    # A row is created only for the caller at the yield boundary;
                    # no row value is retained in the report or reader state.
                    yield {str(key): str(value) for key, value in row.items()}
        except PublicDumpParseError:
            raise
        except csv.Error as error:
            builder.error(reason="malformed_csv")
            self._report = builder.build()
            raise PublicDumpParseError(
                f"Malformed public-dump CSV {self.source.name}: {error}.",
                report=self._report,
            ) from error
        except PublicDumpFormatError:
            builder.error(reason="format_error")
            self._report = builder.build()
            raise
        except (
            OSError,
            EOFError,
            UnicodeError,
            gzip.BadGzipFile,
            tarfile.TarError,
        ) as error:
            builder.error(reason="read_error")
            self._report = builder.build()
            raise PublicDumpFormatError(
                f"Could not read public-dump source {self.source.name}: {error}."
            ) from error
        else:
            self._report = builder.build()

    def read(self) -> PublicDumpReadResult:
        """Read all valid rows and return them with a structured report."""

        rows = tuple(self.iter_rows())
        report = self._report
        if report is None:  # pragma: no cover - iter_rows always exhausts here
            raise PublicDumpError("Public-dump reader did not produce a report.")
        return PublicDumpReadResult(rows=rows, report=report)


@contextmanager
def _open_text(*, path: str) -> Iterator[tuple[io.TextIOBase, BinaryIO]]:
    """Open a CSV stream from a plain, gzip, or tar container.
    The container file is yielded too, so callers can see how far it has been read.
    """

    with ExitStack() as stack:
        container = stack.enter_context(open(path, mode="rb"))
        if tarfile.is_tarfile(path):
            archive = stack.enter_context(tarfile.open(fileobj=container, mode="r:*"))
            members = sorted(
                (member for member in archive.getmembers() if member.isfile()),
                key=lambda member: member.name,
            )
            csv_members = [
                member
                for member in members
                if member.name.lower().endswith((".csv", ".csv.gz", ".csv.gzip"))
            ]
            if csv_members:
                members = csv_members
            if not members:
                raise PublicDumpFormatError(
                    f"Public-dump archive {path} contains no regular files."
                )
            member = members[0]
            extracted = archive.extractfile(member)
            if extracted is None:
                raise PublicDumpFormatError(
                    f"Could not read public-dump archive member {member.name}."
                )
            raw: Any = stack.enter_context(extracted)
            if member.name.lower().endswith((".gz", ".gzip")):
                raw = stack.enter_context(gzip.GzipFile(fileobj=raw, mode="rb"))
        else:
            raw = container
            if path.lower().endswith((".gz", ".gzip")) or _has_gzip_magic(
                path=path
            ):
                raw = stack.enter_context(gzip.GzipFile(fileobj=raw, mode="rb"))
        text_file = stack.enter_context(
            io.TextIOWrapper(raw, encoding="utf-8-sig", newline="")
        )
        yield text_file, container


def _has_gzip_magic(*, path: str) -> bool:
    with open(path, mode="rb") as input_file:
        return input_file.read(2) == b"\x1f\x8b"


def _valid_source_name(name: str) -> bool:
    return (
        bool(name)
        and name not in {".", ".."}
        and os.path.basename(name) == name
        and "/" not in name
        and "\\" not in name
    )


def _validate_header(*, fieldnames: list[str] | None, source_name: str) -> None:
    if not fieldnames:
        raise PublicDumpFormatError(f"Public-dump source {source_name} has no CSV header.")
    if any(not isinstance(name, str) or not name.strip() for name in fieldnames):
        raise PublicDumpFormatError(
            f"Public-dump source {source_name} has an empty CSV header field."
        )
    if len(fieldnames) != len(set(fieldnames)):
        raise PublicDumpFormatError(
            f"Public-dump source {source_name} has duplicate CSV header fields."
        )


def _snapshot_and_verify(*, source: PublicDumpSource, path: str) -> str:
    """Copy a pinned container to private storage before verifying and parsing it."""

    digest = hashlib.sha256()
    temporary_path: str | None = None
    suffix = ""
    lowered_path = path.lower()
    if lowered_path.endswith(".gzip"):
        suffix = ".gzip"
    elif lowered_path.endswith(".gz"):
        suffix = ".gz"
    try:
        with open(path, mode="rb") as source_file:
            with tempfile.NamedTemporaryFile(
                mode="wb",
                suffix=suffix,
                delete=False,
            ) as snapshot:
                temporary_path = snapshot.name
                for chunk in iter(lambda: source_file.read(1024 * 1024), b""):
                    digest.update(chunk)
                    snapshot.write(chunk)
                snapshot.flush()
                os.fsync(snapshot.fileno())
        actual = digest.hexdigest()
        if actual != source.sha256:
            raise PublicDumpChecksumError(
                "Checksum mismatch for public-dump source "
                f"{source.name}: expected {source.sha256}, got {actual}."
            )
    except PublicDumpChecksumError:
        if temporary_path is not None:
            try:
                os.unlink(temporary_path)
            except OSError:
                pass
        raise
    except OSError as error:
        if temporary_path is not None:
            try:
                os.unlink(temporary_path)
            except OSError:
                pass
        raise PublicDumpFormatError(
            f"Could not hash public-dump source {source.name}: {error}."
        ) from error
    if temporary_path is None:  # pragma: no cover - NamedTemporaryFile always names itself
        raise PublicDumpError("Pinned public-dump snapshot was not created.")
    return temporary_path


def iter_public_dump_rows(source: PublicDumpSource | PathInput) -> Iterator[Mapping[str, str]]:
    """Iterate rows through the neutral reader boundary."""

    return PublicDumpReader(source).iter_rows()


def read_public_dump(source: PublicDumpSource | PathInput) -> PublicDumpReadResult:
    """Read all valid rows and return them with a privacy-safe report."""

    return PublicDumpReader(source).read()


def write_public_dump_manifest(manifest: PublicDumpManifest, path: PathInput) -> str:
    """Atomically publish canonical manifest bytes and return its path."""

    output = os.fspath(path)
    if not isinstance(output, str) or not output:
        raise PublicDumpError("Public-dump manifest path must be a non-empty string or path-like value.")
    output_path = os.path.abspath(output)
    parent = os.path.dirname(output_path) or "."
    os.makedirs(parent, exist_ok=True)
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=parent,
            prefix=f".{os.path.basename(output_path)}.",
            delete=False,
        ) as temporary:
            temporary_name = temporary.name
            temporary.write(manifest.to_bytes())
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_name, output_path)
        temporary_name = None
    finally:
        if temporary_name is not None:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass
    return output


def load_public_dump_manifest(path: PathInput) -> PublicDumpManifest:
    """Load and validate a canonical or equivalent JSON manifest."""

    try:
        with open(os.fspath(path), mode="rb") as manifest_file:
            return PublicDumpManifest.from_bytes(manifest_file.read())
    except OSError as error:
        raise PublicDumpError(f"Could not read public-dump manifest {path}: {error}.") from error
